### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by bloodess** [thtliife/servicenow-sync#7] opened 2017-03-23 10:08 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package 0.2.17
**User**: root

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:674:31)
    at Request.self.callback (/packages/servicenow-sync/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/servicenow-sync/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/servicenow-sync/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  9x -9:48.5.0 core:move-right (input.hidden-input)
  3x -9:36.6.0 core:paste (input.hidden-input)
     -6:55.3.0 core:backspace (input.hidden-input)
     -6:53 core:select-all (input.hidden-input)
  3x -6:52.6.0 core:backspace (input.hidden-input)
     -6:44.4.0 core:select-all (input.hidden-input)
     -6:43.4.0 core:paste (input.hidden-input)
     -5:19.7.0 core:backspace (input.hidden-input)
     -4:49.5.0 core:save (input.hidden-input)
     -4:41.4.0 servicenow-sync:configure-file (input.hidden-input)
     -4:39 core:paste (input.hidden-input)
     -3:50.4.0 settings-view:check-for-package-updates (input.hidden-input)
     -1:15.9.0 servicenow-sync:configure-file (input.hidden-input)
     -1:05.0 core:paste (input.hidden-input)
     -0:27.6.0 servicenow-sync:configure-file (input.hidden-input)
     -0:25.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
servicenow-sync 0.2.17 
```

**Comment by thtliife** [comment] 2017-03-23 22:41
Hi @bloodess, 
Could you please add steps to reproduce the error?

**Comment by thtliife** [comment] 2017-03-23 22:45
Duplicate of issue #5

**Closed by thtliife** 2017-03-23 22:45 UTC
Labels: bug
