### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by UberRish** [thtliife/servicenow-sync#9] opened 2017-04-07 10:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package 0.2.17

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Rishi.Joshi\.atom\packages\servicenow-sync\lib\modules\servicenow-sync-utils.coffee:380

TypeError: Cannot read property 'getPath' of undefined
    at Object.syncFileExists (/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:380:28)
    at Object.sync (/packages/servicenow-sync/lib/servicenow-sync.coffee:85:23)
    at /packages/servicenow-sync/lib/servicenow-sync.coffee:66:88)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:46.6.0 servicenow-sync:sync (atom-pane.pane.active)
```

### Non-Core Packages

```
servicenow-sync 0.2.17 
```

**Comment by thtliife** [comment] 2017-04-07 10:55
Duplicate of issue #5

**Closed by thtliife** 2017-04-07 10:55 UTC
