### ISSUE TITLE
Failed to activate the servicenow-sync package

### ISSUE THREAD

**Issue by uranium89** [thtliife/servicenow-sync#1] opened 2016-05-24 05:01 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package, v0.2.5

### Stack Trace

Failed to activate the servicenow-sync package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
  at Error (native)
  at Object.fs.readSync (fs.js:651:19)
  at Object.fs.readFileSync (fs.js:472:24)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
  at Object.module.exports.readFileSync (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\season\lib\cson.js:158:21)
  at Object.module.exports.utils.views.settingsPanel.actions.getavailableFields (C:\Users\vpham20\.atom\packages\servicenow-sync\lib\modules\servicenow-sync-utils.coffee:76:22)
  at new ServicenowSyncSettingsPanel (C:\Users\vpham20\.atom\packages\servicenow-sync\lib\views\servicenow-sync-settings-panel.coffee:18:54)
  at Object.module.exports.ServicenowSync.activate (C:\Users\vpham20\.atom\packages\servicenow-sync\lib\servicenow-sync.coffee:59:40)
  at Package.module.exports.Package.activateNow (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:183:20)
  at C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:156:32
  at Package.module.exports.Package.measure (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:92:15)
  at C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:149:26
  at Package.module.exports.Package.activate (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:538:21)
  at C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:497:46)
  at C:\Users\vpham20\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:754:28

```

### Commands

```
     -0:09.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
servicenow-sync, v0.2.5

# Dev
No dev packages
```

**Comment by thtliife** [comment] 2016-05-24 05:19
Hi uranium89,
Can you tell me if there is a file called `tableConfig.user.cson` in the folder: `C:\Users\vpham20\.atom\packages\servicenow-sync\config`?

**Comment by thtliife** [comment] 2016-05-25 02:49
Should be fixed in v0.2.6

**Comment by lankygibbon** [comment] 2016-06-20 13:04
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package, v0.2.7


### Stack Trace

Failed to activate the servicenow-sync package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at Object.module.exports.readFileSync (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\season\lib\cson.js:158:21)
    at Object.module.exports.utils.views.settingsPanel.actions.getavailableFields (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:76:22)
    at new ServicenowSyncSettingsPanel (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/views/servicenow-sync-settings-panel.coffee:18:54)
    at Object.module.exports.ServicenowSync.activate (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/servicenow-sync.coffee:59:40)
    at Package.module.exports.Package.activateNow (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
servicenow-sync, v0.2.7

# Dev
No dev packages
```



This file C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\season\lib\cson.js referenced in the error log doesn;t seem to exising  in fact the folder app.asar doesn't seem to exist.

**Comment by thtliife** [comment] 2016-06-20 13:19
Hi lankygibbon,
Can you tell me if there is a file called tableConfig.user.cson in the folder: C:\Users\p0076599\.atom\packages\servicenow-sync\config?

**Comment by lankygibbon** [comment] 2016-06-20 13:30
In C:\Users\p0076599\.atom\packages\servicenow-sync\config there is a file called 

tableConfig.cson

but no other files. No file called 

tableConfig.user.cson

**Comment by thtliife** [comment] 2016-06-20 13:49
If you create the file tableConfig.user.cson, does the error go away?

**Comment by lankygibbon** [comment] 2016-06-20 15:51
Unfortunately not. 
I have both tried creating a blank file and also copying the existing file in that folder and renaming it.
I have made sure that my user is the owner and has full control of all files and folders.

Info from error log to see if anything has changed:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package, v0.2.7


### Stack Trace

Failed to activate the servicenow-sync package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at Object.module.exports.readFileSync (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\season\lib\cson.js:158:21)
    at Object.module.exports.utils.views.settingsPanel.actions.getavailableFields (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:76:22)
    at new ServicenowSyncSettingsPanel (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/views/servicenow-sync-settings-panel.coffee:18:54)
    at Object.module.exports.ServicenowSync.activate (file:///C:/Users/p0076599/.atom/packages/servicenow-sync/lib/servicenow-sync.coffee:59:40)
    at Package.module.exports.Package.activateNow (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\p0076599\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
servicenow-sync, v0.2.7

# Dev
No dev packages
```

**Comment by thtliife** [comment] 2016-06-20 20:00
Thanks for the info lankygibbon. 
I'll look into it today

**Comment by thtliife** [comment] 2016-06-20 22:41
Found the issue.
Thank you for your help with the troubleshooting @lankygibbon :)
I don't use windows, so your help was awesome.
Have resolved the issue, and tested in a vm. All should be working fine.
Can you please update to v0.2.8, and let me know how it goes. I will keep this issue open until i hear back with your results.

**Comment by lankygibbon** [comment] 2016-06-21 08:39
Wow that was quick.
Yeah all seems to be working now.

Thanks for the help and the wonderfull add-on

**Comment by thtliife** [comment] 2016-06-21 08:49
Great!
Closing this issue now 🙂

**Closed by thtliife** 2016-06-21 08:49 UTC
Labels: bug
